"""
Report Generator - Core PDF generation logic
"""

from datetime import datetime
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from reportlab.pdfgen import canvas
import io

from backend.reports.reconciliation_report import ReconciliationReport
from backend.reports.forecast_report import ForecastReport
from backend.reports.tax_fee_report import TaxFeeReport
from backend.reports.full_report import FullReport


class ReportGenerator:
    """Main report generator that orchestrates all report types"""

    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_styles()
        self.timestamp = datetime.now().strftime("%d %B %Y, %I:%M %p")
        self.company_name = "CashSight"
        self.footer_text = f"Generated by {self.company_name} • {self.timestamp}"

    def _setup_styles(self):
        """Setup custom styles for reports"""
        
        # Company Name Style
        if 'CompanyName' not in self.styles:
            self.styles.add(ParagraphStyle(
                name='CompanyName',
                parent=self.styles['Heading1'],
                fontSize=28,
                alignment=TA_CENTER,
                spaceAfter=4,
                textColor=colors.HexColor('#1a237e'),
                fontName='Helvetica-Bold'
            ))
        
        # Report Title Style
        if 'ReportTitle' not in self.styles:
            self.styles.add(ParagraphStyle(
                name='ReportTitle',
                parent=self.styles['Heading2'],
                fontSize=18,
                alignment=TA_CENTER,
                spaceAfter=6,
                textColor=colors.HexColor('#333333'),
                fontName='Helvetica-Bold'
            ))
        
        # Subtitle Style
        if 'ReportSubtitle' not in self.styles:
            self.styles.add(ParagraphStyle(
                name='ReportSubtitle',
                parent=self.styles['Normal'],
                fontSize=11,
                alignment=TA_CENTER,
                textColor=colors.HexColor('#666666'),
                spaceAfter=20,
                fontName='Helvetica'
            ))
        
        # Section Header Style
        if 'SectionHeader' not in self.styles:
            self.styles.add(ParagraphStyle(
                name='SectionHeader',
                parent=self.styles['Heading2'],
                fontSize=14,
                spaceAfter=8,
                spaceBefore=16,
                textColor=colors.HexColor('#1a237e'),
                fontName='Helvetica-Bold'
            ))
        
        # Subsection Header
        if 'SubsectionHeader' not in self.styles:
            self.styles.add(ParagraphStyle(
                name='SubsectionHeader',
                parent=self.styles['Heading3'],
                fontSize=12,
                spaceAfter=6,
                textColor=colors.HexColor('#333333'),
                fontName='Helvetica-Bold'
            ))
        
        # Body Text
        if 'BodyText' not in self.styles:
            self.styles.add(ParagraphStyle(
                name='BodyText',
                parent=self.styles['Normal'],
                fontSize=10,
                leading=14,
                spaceAfter=8,
                alignment=TA_JUSTIFY,
                fontName='Helvetica'
            ))
        
        # Small Body Text
        if 'BodyTextSmall' not in self.styles:
            self.styles.add(ParagraphStyle(
                name='BodyTextSmall',
                parent=self.styles['Normal'],
                fontSize=9,
                leading=12,
                spaceAfter=4,
                fontName='Helvetica'
            ))
        
        # Footer Style
        if 'FooterStyle' not in self.styles:
            self.styles.add(ParagraphStyle(
                name='FooterStyle',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.HexColor('#999999'),
                alignment=TA_CENTER,
                fontName='Helvetica'
            ))

    def _create_footer(self, canvas, doc, doc_title):
        """Add page numbers and footer to each page"""
        canvas.saveState()
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.HexColor('#888888'))
        
        # Page number
        page_num = f"Page {doc.page}"
        canvas.drawRightString(7.5 * inch, 0.4 * inch, page_num)
        
        # Footer text
        canvas.drawString(1 * inch, 0.4 * inch, self.footer_text)
        canvas.drawCentredString(4.25 * inch, 0.4 * inch, doc_title)
        
        # Footer line
        canvas.setStrokeColor(colors.HexColor('#dddddd'))
        canvas.setLineWidth(0.5)
        canvas.line(1 * inch, 0.6 * inch, 7.5 * inch, 0.6 * inch)
        
        canvas.restoreState()

    def _create_base_document(self, title, filename):
        """Create base document with proper formatting"""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            topMargin=1.2 * cm,
            bottomMargin=1.2 * cm,
            leftMargin=1.5 * cm,
            rightMargin=1.5 * cm,
            title=title,
            author="CashSight"
        )
        
        story = []
        
        # Company Name
        story.append(Paragraph("CashSight", self.styles['CompanyName']))
        story.append(Paragraph("Financial Operations Report", self.styles['ReportTitle']))
        story.append(Paragraph(title, self.styles['ReportSubtitle']))
        story.append(Paragraph(f"Generated: {self.timestamp}", self.styles['BodyTextSmall']))
        story.append(Spacer(1, 0.3 * cm))
        
        # Divider
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#dddddd'), spaceAfter=0.3*cm))
        
        return doc, story, buffer

    def _create_table(self, data, col_widths=None, header_color='#1a237e'):
        """Create a styled table"""
        if not data or len(data) < 2:
            return Paragraph("No data available", self.styles['BodyText'])
        
        if col_widths is None:
            col_widths = [2 * inch] * len(data[0])
        
        table = Table(data, colWidths=col_widths, repeatRows=1)
        table.setStyle(TableStyle([
            # Header
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor(header_color)),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('TOPPADDING', (0, 0), (-1, 0), 8),
            
            # Body
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('ALIGN', (1, 1), (-1, -1), 'RIGHT'),
            ('ALIGN', (0, 1), (0, -1), 'LEFT'),
            ('TOPPADDING', (0, 1), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 5),
            
            # Grid
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e0e0e0')),
            
            # Alternating row colors
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
            
            # Align first column left
            ('ALIGN', (0, 1), (0, -1), 'LEFT'),
        ]))
        
        return table

    def _format_currency(self, amount):
        """Format amount as Indian Rupee"""
        return f"Rs. {amount:,.2f}"

    def _create_summary_box(self, title, items):
        """Create a summary box with key metrics"""
        story = []
        story.append(Paragraph(title, self.styles['SubsectionHeader']))
        
        table_data = [['Metric', 'Value']]
        for label, value in items:
            table_data.append([label, value])
        
        table = self._create_table(table_data, col_widths=[3.5 * inch, 3.5 * inch])
        story.append(table)
        story.append(Spacer(1, 0.2 * cm))
        
        return story

    def generate_reconciliation_report(self, matches, exceptions, settlements, bank):
        """Generate Reconciliation Report PDF"""
        doc, story, buffer = self._create_base_document(
            "Reconciliation Analysis Report", 
            "CashSight_Reconciliation_Report.pdf"
        )
        
        report = ReconciliationReport()
        story.extend(report.build(matches, exceptions, settlements, bank, self))
        
        doc.build(
            story, 
            onFirstPage=lambda canvas, doc: self._create_footer(canvas, doc, "Reconciliation Report"),
            onLaterPages=lambda canvas, doc: self._create_footer(canvas, doc, "Reconciliation Report")
        )
        
        buffer.seek(0)
        return buffer

    def generate_forecast_report(self, matches, exceptions, settlements, forecast_result):
        """Generate Forecast Report PDF"""
        doc, story, buffer = self._create_base_document(
            "Cash Flow Forecast Report",
            "CashSight_Forecast_Report.pdf"
        )
        
        report = ForecastReport()
        story.extend(report.build(matches, exceptions, settlements, forecast_result, self))
        
        doc.build(
            story,
            onFirstPage=lambda canvas, doc: self._create_footer(canvas, doc, "Forecast Report"),
            onLaterPages=lambda canvas, doc: self._create_footer(canvas, doc, "Forecast Report")
        )
        
        buffer.seek(0)
        return buffer

    def generate_tax_fee_report(self, tax_result):
        """Generate Tax & Fee Analysis Report PDF"""
        doc, story, buffer = self._create_base_document(
            "Tax and Fee Analysis Report",
            "CashSight_Tax_Fee_Analysis.pdf"
        )
        
        report = TaxFeeReport()
        story.extend(report.build(tax_result, self))
        
        doc.build(
            story,
            onFirstPage=lambda canvas, doc: self._create_footer(canvas, doc, "Tax and Fee Analysis"),
            onLaterPages=lambda canvas, doc: self._create_footer(canvas, doc, "Tax and Fee Analysis")
        )
        
        buffer.seek(0)
        return buffer

    def generate_full_report(self, matches, exceptions, settlements, bank, tax_result, forecast_result):
        """Generate Full CashSight Report PDF"""
        doc, story, buffer = self._create_base_document(
            "Complete Financial Operations Report",
            "CashSight_Full_Report.pdf"
        )
        
        report = FullReport()
        story.extend(report.build(matches, exceptions, settlements, bank, tax_result, forecast_result, self))
        
        doc.build(
            story,
            onFirstPage=lambda canvas, doc: self._create_footer(canvas, doc, "Full Report"),
            onLaterPages=lambda canvas, doc: self._create_footer(canvas, doc, "Full Report")
        )
        
        buffer.seek(0)
        return buffer